apiVersion: v1
kind: Service
metadata:
  name: mfe-system-applications-service
  labels:
    app: mfe-system-applications-service
spec:
  selector:
    app: mfe-system-applications-service
  # type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      # nodePort: 30000
